CREATE TABLE IF NOT EXISTS mediatypes (
	typeID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING UNIQUE,
	STOCK BOOL NOT NULL DEFAULT 0,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS genres (
	genreID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING UNIQUE,
	STOCK BOOL NOT NULL DEFAULT 0,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS categories (
	categoryID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING UNIQUE,
	STOCK BOOL NOT NULL DEFAULT 0,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS info (
	instanceID INTEGER PRIMARY KEY,
	VERSION STRING,
	HOSTNAME STRING UNIQUE,
	OS STRING,
	ARCH STRING,
	GOVERSION STRING,
	SQLITEVERSION STRING,
	TIMEZONE STRING);

CREATE TABLE IF NOT EXISTS collections (
	collectionID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT UNIQUE,
	DESCRIPTION TEXT,
	categoryID INTEGER DEFAULT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	EDITED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(categoryID) REFERENCES categories(categoryID));

CREATE TABLE IF NOT EXISTS entries (
	entryID INTEGER PRIMARY KEY AUTOINCREMENT,
	TITLE TEXT NOT NULL,
	YEAR INTEGER NOT NULL,
	PLOT TEXT NOT NULL,
	IS_DIGITAL BOOL NOT NULL DEFAULT 0,
	collectionID INTEGER DEFAULT NULL,
	genreID INTEGER DEFAULT NULL,
	typeID INTEGER DEFAULT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	EDITED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(collectionID) REFERENCES collections(collectionID),
	FOREIGN KEY(genreID) REFERENCES genres(genreID),
	FOREIGN KEY(typeID) REFERENCES mediatypes(typeID));